version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - flake8 --exclude=venv* --statistics
      - pytest -v --cov=calculator

artifacts:
  files:
    - '**/*'
